### ISSUE TITLE
请问支持蓝牙MESH吗？

### ISSUE THREAD

**Issue by Leadrive** [espressif/esp-bridge#18]
用esp32-s3可以实现下面功能吗？

对外支持：4G + WIFI + 以太网，优先：以太网>WIFI>4G

对内支持：BLUETOOTH MESH + WIFI MESH

**Comment by tswen** [comment]
At present, BLE mesh is still under development, and I believe it will be released in the near future.

**Comment by Leadrive** [comment]
好的，谢谢
